server:
  port: 8083
# DataSource Config
spring:
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.48.51.66:3306/copyright?useUnicode=true&useSSL=false&characterEncoding=utf8&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: lvfei
    password: 123456
  redis:
    host: 120.48.51.66
    port: 6379
    timeout: 3000 #连接超时
    lettuce:
      pool:
        max-active: 100 #连接池最大连接数(使用负值表示没有限制>
        max-idle: 20 # 连接池中的最大空闲连接
        min-idle: 0 #连接池中的最小空闲连接
        max-wait: 30000 #连接池最大阻塞等待时间（使用负值表示没有限制)
mybatis-plus:
  mapper-locations: classpath*:/mapper/copyright/**Mapper.xml

copyright:
  jwt:
     secret: f4e2e52034348f86b67cde581c0f9eb5
     expire: 604800
     header: Authorization



shiro-redis:

  enabled: true
  redis-manager:
    host: 127.0.0.1:6379


